import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Compass, Headphones, Sparkles } from "lucide-react";
import ArtistCarousel from "@/components/ArtistCarousel";
import RecommendationGrid from "@/components/RecommendationGrid";
import StoryCard from "@/components/StoryCard";
import { circles, stories } from "@/lib/community";

export const metadata: Metadata = { title: "Discover", description: "Thoughtful music recommendations shaped by human stories." };

export default function DiscoverPage() {
  return <div><section className="relative overflow-hidden border-b border-stone-900/8"><div className="hero-glow"/><div className="relative mx-auto max-w-[1300px] px-6 py-16 sm:px-8 lg:py-24"><p className="micro-label text-[#a74735]"><Sparkles className="mr-2 inline size-3"/>A more human recommendation engine</p><h1 className="mt-5 max-w-4xl font-serif text-6xl leading-[.9] tracking-[-.045em] sm:text-8xl">Follow your heart,<br/><em className="font-normal text-[#a74735]">find your own music.</em></h1><p className="mt-7 max-w-2xl text-base leading-7 text-stone-600">Explore music through moments, moods, rituals, and the people who carried these songs before you.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/stories" className="inline-flex h-12 items-center gap-8 rounded-full bg-[#2b2025] px-6 text-xs font-semibold text-white">Read listening stories <ArrowRight className="size-4"/></Link><Link href="/circles" className="inline-flex h-12 items-center gap-2 rounded-full border border-stone-900/12 bg-white/50 px-5 text-xs font-semibold"><Compass className="size-4"/>Browse circles</Link></div></div></section>
  <ArtistCarousel/>
  <section className="mx-auto max-w-[1300px] px-6 py-16 sm:px-8 lg:py-24"><div className="mb-9 flex items-end justify-between"><div><p className="micro-label text-[#a74735]">Six ways in</p><h2 className="mt-3 font-serif text-4xl">Recommended with context.</h2></div><span className="hidden text-xs text-stone-400 sm:block">Save what speaks to you</span></div><RecommendationGrid/></section>
  <section className="bg-[#2a2025] text-[#f7f1e8]"><div className="mx-auto max-w-[1300px] px-6 py-16 sm:px-8 lg:py-24"><div className="mb-9 flex items-end justify-between"><div><p className="micro-label text-[#d48169]">Stories worth staying for</p><h2 className="mt-3 font-serif text-4xl">Listen through someone else&apos;s life.</h2></div><Link href="/stories" className="inline-flex items-center gap-2 text-xs text-stone-300">All stories <ArrowRight className="size-4"/></Link></div><div className="grid gap-5 lg:grid-cols-2">{stories.slice(0,2).map(story=><div key={story.slug} className="text-[#251d21]"><StoryCard story={story}/></div>)}</div></div></section>
  <section className="mx-auto max-w-[1300px] px-6 py-16 sm:px-8 lg:py-24"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><Headphones className="size-6 text-[#a74735]"/><h2 className="mt-5 font-serif text-4xl">Rooms with a rhythm.</h2><p className="mt-4 text-sm leading-7 text-stone-500">Join a smaller conversation organized around how—and when—you listen.</p><Link href="/circles" className="mt-7 inline-flex items-center gap-7 rounded-full border border-stone-900/12 px-5 py-3 text-xs font-semibold">Explore every circle <ArrowRight className="size-4"/></Link></div><div className="grid gap-3 sm:grid-cols-2">{circles.slice(0,4).map(circle=><Link href={`/circles#${circle.slug}`} key={circle.slug} className="rounded-2xl border border-stone-900/8 bg-white/55 p-5 transition hover:-translate-y-0.5 hover:bg-white hover:shadow-lg"><span className="mb-4 block size-2 rounded-full" style={{backgroundColor:circle.accent}}/><h3 className="font-serif text-xl">{circle.name}</h3><p className="mt-2 text-xs leading-5 text-stone-500">{circle.description}</p><p className="mt-4 text-[9px] uppercase tracking-wider text-stone-400">{circle.members.toLocaleString()} listeners · {circle.cadence}</p></Link>)}</div></div></section></div>;
}
