import { ArrowRight, Bookmark, ChevronRight, Disc3, Headphones, Heart, MessageCircle, MoreHorizontal, Music2, Pause, Play, Radio, Sparkles, Users } from 'lucide-react';
import { Badge } from '@/components/reui/badge';
import { Avatar, AvatarFallback, AvatarGroup, AvatarGroupCount } from '@/components/ui/avatar';
import { Card, CardContent } from '@/components/ui/card';

const tracks=[
 {title:'Blue Hour',artist:'Leif Vollebekk',genre:'Indie folk',mood:'Slow mornings',color:'from-[#a99b8b] to-[#61564d]'},
 {title:'Show Me How',artist:'Men I Trust',genre:'Dream pop',mood:'Night drives',color:'from-[#708e8b] to-[#304a4e]'},
 {title:'Sweet Disposition',artist:'The Temper Trap',genre:'Indie rock',mood:'Open roads',color:'from-[#bf765d] to-[#683c3d]'},
 {title:'Doomed',artist:'Moses Sumney',genre:'Art soul',mood:'Solitude',color:'from-[#7b738a] to-[#3b3447]'},
];
const circles=[['Sunday Morning Club','Warm, gentle records for slow starts','SM','#d6aa69'],['Songs for Starting Over','Tender resets and brave beginnings','SO','#769295'],['After Midnight','For the hours that ask better questions','AM','#8b6877']];

function ReuiBadge({children}:{children:React.ReactNode}){return <Badge variant="primary-light" radius="full" size="default" render={undefined} className="border-[#a74735]/10 bg-[#a74735]/8 px-2.5 text-[9px] font-bold uppercase tracking-[.14em] text-[#8d3c2d]">{children}</Badge>}
function Person({initials,name,time,color}:{initials:string;name:string;time:string;color:string}){return <div className="flex items-center gap-3"><Avatar className="size-9" size="default"><AvatarFallback className={`${color} text-[10px] font-bold text-white`}>{initials}</AvatarFallback></Avatar><div><p className="text-xs font-semibold text-stone-800">{name}</p><p className="mt-0.5 text-[10px] text-stone-400">{time}</p></div></div>}
function MiniPlayer({title,artist,tone}:{title:string;artist:string;tone:string}){return <div className={`mt-5 flex items-center gap-3 rounded-2xl ${tone} p-3`}><button className="grid size-10 shrink-0 place-items-center rounded-full bg-[#2b2025] text-white shadow-md transition hover:scale-105" aria-label={`Play ${title}`}><Play className="ml-0.5 size-3.5 fill-current"/></button><div className="min-w-0"><p className="truncate text-xs font-semibold">{title}</p><p className="mt-0.5 text-[10px] text-stone-500">{artist}</p></div><div className="ml-auto hidden items-end gap-[3px] sm:flex" aria-hidden="true">{[12,20,15,27,18,24,10,20,14].map((h,i)=><i key={i} className="w-[2px] rounded-full bg-[#a74735]/45" style={{height:h}}/>)}</div><span className="text-[9px] text-stone-400">4:18</span></div>}

export default function HomePage(){return <>
 <section className="relative overflow-hidden border-b border-stone-900/8"><div className="hero-glow"/><div className="mx-auto grid min-h-[660px] max-w-[1400px] items-center gap-12 px-6 py-16 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:py-20"><div className="relative z-10 max-w-2xl"><ReuiBadge><Sparkles className="size-3"/>Made for curious ears</ReuiBadge><h1 className="mt-7 font-serif text-[clamp(4rem,7vw,7.4rem)] leading-[.86] tracking-[-.055em] text-[#251d21]">Find the song<br/>that finds <em className="font-normal text-[#a74735]">you.</em></h1><p className="mt-7 max-w-xl text-base leading-7 text-stone-600 sm:text-lg">Music discovery through human stories. Share what moves you, hear why it matters, and follow your curiosity somewhere unexpected.</p><div className="mt-9 flex flex-wrap items-center gap-3"><a href="#stories" className="inline-flex h-12 items-center gap-8 rounded-full bg-[#2b2025] px-6 text-xs font-semibold text-white shadow-xl shadow-[#2b2025]/10 transition hover:-translate-y-0.5 hover:bg-[#a74735]">Start exploring <ArrowRight className="size-4"/></a><a href="#circles" className="inline-flex h-12 items-center gap-2 rounded-full border border-stone-900/12 bg-white/45 px-5 text-xs font-semibold hover:bg-white"><Users className="size-4"/>Find your circle</a></div><div className="mt-12 flex items-center gap-4"><AvatarGroup className="-space-x-2.5"><Avatar className="size-9" size="default"><AvatarFallback className="bg-[#6b7889] text-[9px] text-white">AK</AvatarFallback></Avatar><Avatar className="size-9" size="default"><AvatarFallback className="bg-[#c48b68] text-[9px] text-white">JL</AvatarFallback></Avatar><Avatar className="size-9" size="default"><AvatarFallback className="bg-[#697f72] text-[9px] text-white">MO</AvatarFallback></Avatar><AvatarGroupCount className="size-9 bg-[#2b2025] text-[9px] text-white">+12k</AvatarGroupCount></AvatarGroup><div className="text-[11px] leading-4 text-stone-500"><strong className="font-semibold text-stone-800">12,400 listeners</strong><br/>shared something this week</div></div></div>
 <div className="relative mx-auto aspect-square w-full max-w-[560px]"><div className="absolute inset-[8%] rounded-full border border-[#2b2025]/8"/><div className="absolute inset-[19%] rounded-full border border-[#2b2025]/8"/><div className="absolute left-1/2 top-1/2 aspect-square w-[69%] -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#292225] p-[9%] shadow-2xl shadow-[#2b2025]/30"><div className="absolute inset-[6%] rounded-full border border-white/8"/><div className="absolute inset-[18%] rounded-full border border-white/8"/><div className="absolute inset-[31%] rounded-full bg-[#a74735] shadow-inner"><div className="absolute inset-[37%] rounded-full bg-[#f3d7a2]"/></div><span className="absolute left-1/2 top-[12%] -translate-x-1/2 text-[9px] uppercase tracking-[.25em] text-stone-400">Sasagayo sessions</span></div><Card className="absolute -left-2 top-[9%] w-52 rotate-[-4deg] border-0 bg-white/90 py-0 shadow-xl backdrop-blur" size="sm"><CardContent className="p-4"><div className="mb-3 flex items-center justify-between"><ReuiBadge>Story #248</ReuiBadge><Music2 className="size-3.5 text-[#a74735]"/></div><p className="font-serif text-lg leading-5">“It sounds like a window opening.”</p><p className="mt-3 text-[9px] uppercase tracking-wider text-stone-400">— Mara, Lisbon</p></CardContent></Card><Card className="absolute -right-2 bottom-[12%] w-56 rotate-[3deg] border-0 bg-[#eee5d8]/95 py-0 shadow-xl" size="sm"><CardContent className="flex items-center gap-3 p-3"><button className="grid size-10 place-items-center rounded-full bg-[#a74735] text-white"><Pause className="size-3.5 fill-current"/></button><div><p className="text-[9px] uppercase tracking-wider text-[#a74735]">Now playing</p><p className="mt-1 font-serif text-base">Orange Moon</p></div><div className="ml-auto flex gap-0.5"><i className="wavebar"/><i className="wavebar h-5"/><i className="wavebar h-3"/><i className="wavebar h-6"/></div></CardContent></Card></div></div></section>

 <section id="picks" className="mx-auto max-w-[1400px] scroll-mt-24 px-6 py-20 sm:px-8 lg:py-28"><div className="mb-10 flex items-end justify-between"><div><p className="micro-label text-[#a74735]">Curated for today</p><h2 className="mt-3 font-serif text-4xl tracking-[-.03em] sm:text-5xl">Start with these.</h2></div><a href="#" className="hidden items-center gap-2 text-xs font-semibold text-stone-500 hover:text-stone-900 sm:flex">View all picks <ArrowRight className="size-4"/></a></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{tracks.map((track,index)=><article key={track.title} className="group"><div className={`relative aspect-[1/1.05] overflow-hidden rounded-[28px] bg-gradient-to-br ${track.color} p-5 shadow-sm`}><span className="text-[10px] font-bold uppercase tracking-[.2em] text-white/55">0{index+1} · Daily pick</span><div className="absolute -bottom-[23%] -right-[20%] aspect-square w-[90%] rounded-full bg-[#211d1d] shadow-2xl transition duration-500 group-hover:-translate-x-3 group-hover:-translate-y-3 group-hover:rotate-12"><div className="absolute inset-[13%] rounded-full border border-white/8"/><div className="absolute inset-[25%] rounded-full border border-white/8"/><div className="absolute inset-[38%] rounded-full bg-[#d6aa69]"/></div><button className="absolute bottom-5 left-5 grid size-11 place-items-center rounded-full bg-white text-[#2b2025] shadow-lg transition group-hover:scale-105" aria-label={`Play ${track.title}`}><Play className="ml-0.5 size-4 fill-current"/></button></div><div className="px-1 pt-4"><div className="flex items-center justify-between"><ReuiBadge>{track.genre}</ReuiBadge><button aria-label="More options"><MoreHorizontal className="size-4 text-stone-400"/></button></div><h3 className="mt-3 font-serif text-xl">{track.title}</h3><p className="mt-1 text-xs text-stone-500">{track.artist} · {track.mood}</p></div></article>)}</div></section>

 <section id="stories" className="scroll-mt-18 bg-[#2a2025] text-[#f7f1e8]"><div className="mx-auto grid max-w-[1400px] gap-14 px-6 py-20 sm:px-8 lg:grid-cols-[.65fr_1.35fr] lg:gap-20 lg:py-28"><div className="lg:sticky lg:top-28 lg:self-start"><ReuiBadge>Community stories</ReuiBadge><h2 className="mt-6 font-serif text-5xl leading-[.94] tracking-[-.04em] sm:text-6xl">The life<br/>inside the<br/><em className="font-normal text-[#d7826b]">music.</em></h2><p className="mt-7 max-w-sm text-sm leading-7 text-stone-400">Recommendations with context. Memories with a soundtrack. People telling the truth about what they hear.</p><div className="mt-9 flex gap-7 text-xs"><div><strong className="block font-serif text-2xl text-white">2.8k</strong><span className="text-stone-500">stories this month</span></div><div><strong className="block font-serif text-2xl text-white">86</strong><span className="text-stone-500">countries listening</span></div></div></div><div className="grid gap-5">
 <Card className="border-0 bg-[#f7f2e9] py-0 text-[#2b2025] shadow-none" size="default"><CardContent className="p-6 sm:p-8"><div className="flex items-center justify-between"><Person initials="AK" name="Amara K." time="Nairobi · 18 minutes ago" color="bg-[#866072]"/><button aria-label="More"><MoreHorizontal className="size-5 text-stone-400"/></button></div><ReuiBadge>Memory</ReuiBadge><h3 className="mt-5 max-w-xl font-serif text-3xl leading-[1.05] tracking-[-.02em] sm:text-4xl">The song my father left in the glovebox</h3><p className="mt-4 max-w-2xl text-sm leading-7 text-stone-600">I found the cassette two summers after he passed. Side B began with the track he always hummed while cooking—and suddenly, the whole kitchen was there again.</p><MiniPlayer title="Orange Moon" artist="Erykah Badu · Mama's Gun" tone="bg-[#e7d8c5]"/><div className="mt-5 flex items-center gap-5 border-t border-stone-900/8 pt-4 text-xs text-stone-500"><button className="social-action"><Heart className="size-4"/>284</button><button className="social-action"><MessageCircle className="size-4"/>38</button><button className="social-action ml-auto"><Bookmark className="size-4"/>Save</button></div></CardContent></Card>
 <div className="grid gap-5 md:grid-cols-2"><Card className="border-0 bg-[#d7e0df] py-0 text-[#2b2025] shadow-none" size="default"><CardContent className="p-6"><Person initials="JL" name="Jonah Lee" time="Seoul · 1 hour ago" color="bg-[#57757b]"/><h3 className="mt-7 font-serif text-2xl leading-tight">For taking the long way home</h3><p className="mt-3 text-xs leading-6 text-stone-600">A rainy train north turned every passing window into a tiny film.</p><MiniPlayer title="Avril 14th" artist="Aphex Twin" tone="bg-white/45"/><div className="mt-5 flex gap-5 text-xs text-stone-500"><span className="social-action"><Heart className="size-4"/>176</span><span className="social-action"><MessageCircle className="size-4"/>21</span></div></CardContent></Card><Card className="border-0 bg-[#ddc9c0] py-0 text-[#2b2025] shadow-none" size="default"><CardContent className="p-6"><Person initials="NS" name="Noor S." time="Beirut · 3 hours ago" color="bg-[#a35442]"/><h3 className="mt-7 font-serif text-2xl leading-tight">When a city becomes a chorus</h3><p className="mt-3 text-xs leading-6 text-stone-600">This was playing from three different balconies on the first warm night.</p><MiniPlayer title="Habibi" artist="Tamino" tone="bg-white/40"/><div className="mt-5 flex gap-5 text-xs text-stone-500"><span className="social-action"><Heart className="size-4"/>342</span><span className="social-action"><MessageCircle className="size-4"/>46</span></div></CardContent></Card></div></div></div></section>

 <section id="circles" className="mx-auto max-w-[1400px] scroll-mt-18 px-6 py-20 sm:px-8 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="micro-label text-[#a74735]">Listening circles</p><h2 className="mt-4 max-w-md font-serif text-5xl leading-[.95] tracking-[-.035em]">Find people on your <em className="font-normal text-[#a74735]">frequency.</em></h2><p className="mt-6 max-w-md text-sm leading-7 text-stone-500">Small communities built around a feeling, a ritual, or a way of listening. Join the conversation or begin your own.</p><a href="#" className="mt-8 inline-flex h-11 items-center gap-8 rounded-full border border-stone-900/12 px-5 text-xs font-semibold hover:bg-white">Explore all circles <ArrowRight className="size-4"/></a></div><div className="grid gap-3">{circles.map(([name,desc,initials,color],i)=><Card key={name} className="group border-0 bg-white/55 py-0 shadow-none ring-1 ring-stone-900/8 transition hover:-translate-y-0.5 hover:bg-white hover:shadow-lg" size="sm"><CardContent className="flex items-center gap-4 p-4 sm:p-5"><div className="grid size-12 shrink-0 place-items-center rounded-2xl font-serif text-sm text-white" style={{backgroundColor:color}}>{initials}</div><div><h3 className="font-serif text-lg">{name}</h3><p className="mt-1 text-[11px] text-stone-500">{desc}</p></div><div className="ml-auto hidden items-center gap-5 sm:flex"><span className="flex items-center gap-1.5 text-[10px] text-stone-400"><Users className="size-3.5"/>{[842,615,1204][i]}</span><span className="flex items-center gap-1.5 text-[10px] text-emerald-600"><Radio className="size-3.5"/>Live</span><ChevronRight className="size-4 text-stone-400 transition group-hover:translate-x-1"/></div></CardContent></Card>)}</div></div></section>

 <section id="share" className="mx-4 mb-4 overflow-hidden rounded-[32px] bg-[#a74735] text-[#fff8ee] sm:mx-6 sm:mb-6"><div className="mx-auto flex min-h-[380px] max-w-6xl flex-col items-center justify-center px-6 py-20 text-center"><Headphones className="size-7"/><p className="micro-label mt-6 text-[#f0baa9]">Your soundtrack belongs here</p><h2 className="mt-4 font-serif text-5xl leading-[.94] tracking-[-.04em] sm:text-7xl">What song are you<br/>carrying today?</h2><p className="mt-5 max-w-xl text-sm leading-6 text-[#f2c7ba]">Give it a story. Someone out there might need to hear both.</p><button className="mt-8 inline-flex h-12 items-center gap-8 rounded-full bg-[#fff8ee] px-6 text-xs font-semibold text-[#2b2025] shadow-xl transition hover:-translate-y-0.5">Share a song <ArrowRight className="size-4"/></button></div></section>

 <div className="sticky bottom-3 z-40 mx-auto mb-3 flex h-16 w-[calc(100%-24px)] max-w-3xl items-center gap-3 rounded-2xl border border-white/10 bg-[#21191d]/95 px-3 text-white shadow-2xl backdrop-blur-xl sm:px-4"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-[#c27a61] to-[#5a3944]"><Disc3 className="size-5"/></div><div className="min-w-0"><p className="truncate text-xs font-semibold">Orange Moon</p><p className="text-[9px] text-stone-400">Erykah Badu</p></div><div className="mx-auto hidden items-center gap-2 sm:flex"><button className="grid size-9 place-items-center rounded-full bg-white text-[#21191d]" aria-label="Pause"><Pause className="size-3.5 fill-current"/></button></div><div className="hidden min-w-32 items-center gap-3 text-[9px] text-stone-500 md:flex"><span>1:42</span><div className="h-1 flex-1 overflow-hidden rounded-full bg-white/10"><div className="h-full w-2/5 rounded-full bg-[#cf735c]"/></div><span>4:18</span></div><button className="icon-button-dark" aria-label="Save"><Heart className="size-4"/></button><button className="icon-button-dark" aria-label="Queue"><Music2 className="size-4"/></button></div>
 </>}
